In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)

In [ ]:
# Determine the number of unique values in each column.
unique = application_df.nunique()
print(unique)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
applications = application_df['APPLICATION_TYPE'].value_counts()
print(applications)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
applications = application_df['APPLICATION_TYPE'].value_counts()
print(applications)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = applications[applications < 500].index.tolist()
print(application_types_to_replace)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = classification_counts[classification_counts > 1]
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 100].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
encoded = pd.get_dummies(application_df)
print(encoded.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                   False
1       1   108590              1                   False
2       1     5000              0                   False
3       1     6692              1                   False
4       1   142590              1                   False

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                  True                 False                False
1                 False                 False                 True
2                 False                 False                False
3                 False                 False                 True
4                 False                 False                 True

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                False                False                False  ...
1                False                False                False  ...
2                False                 True                False  ...
3                False                False                False  ...
4                False                False                False  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0              False                   False                     False
1               True                   False                     False
2              False                   False                     False
3              False                    True                     False
4              False                   False                      True

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0               False             False                   False
1               False             False                   False
2               False             False                   False
3               False             False                   False
4               False             False                   False

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0            False              False                      True
1            False              False                      True
2            False              False                      True
3            False              False                      True
4            False              False                      True

   SPECIAL_CONSIDERATIONS_Y
0                     False
1                     False
2                     False
3                     False
4                     False

[5 rows x 76 columns]

In [ ]:
# Split our preprocessed data into our features and target arrays
X = encoded.drop(['IS_SUCCESSFUL'], axis=1)
y = encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = applications[applications < 500].index.tolist()
print(application_types_to_replace)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=15, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                3800

 dense_1 (Dense)             (None, 15)                765

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 4581 (17.89 KB)
Trainable params: 4581 (17.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
nnmodel = nn.fit(X_train_scaled, y_train, epochs=100, batch_size=10, validation_data=(X_test_scaled, y_test))

Epoch 1/100
2744/2744 [==============================] - 10s 3ms/step - loss: 0.5721 - accuracy: 0.7197 - val_loss: 0.5585 - val_accuracy: 0.7259
Epoch 2/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5517 - accuracy: 0.7287 - val_loss: 0.5544 - val_accuracy: 0.7283
Epoch 3/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5496 - accuracy: 0.7298 - val_loss: 0.5556 - val_accuracy: 0.7258
Epoch 4/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5474 - accuracy: 0.7309 - val_loss: 0.5586 - val_accuracy: 0.7243
Epoch 5/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5462 - accuracy: 0.7321 - val_loss: 0.5550 - val_accuracy: 0.7292
Epoch 6/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5447 - accuracy: 0.7330 - val_loss: 0.5607 - val_accuracy: 0.7309
Epoch 7/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5451 - accuracy: 0.7323 - val_loss: 0.5520 - val_accuracy: 0.7303
Epoch 8/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5438 - accuracy: 0.7337 - val_loss: 0.5527 - val_accuracy: 0.7300
Epoch 9/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5431 - accuracy: 0.7342 - val_loss: 0.5515 - val_accuracy: 0.7327
Epoch 10/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5428 - accuracy: 0.7344 - val_loss: 0.5522 - val_accuracy: 0.7294
Epoch 11/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5429 - accuracy: 0.7347 - val_loss: 0.5534 - val_accuracy: 0.7294
Epoch 12/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5418 - accuracy: 0.7334 - val_loss: 0.5518 - val_accuracy: 0.7299
Epoch 13/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5416 - accuracy: 0.7347 - val_loss: 0.5553 - val_accuracy: 0.7316
Epoch 14/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5412 - accuracy: 0.7353 - val_loss: 0.5540 - val_accuracy: 0.7329
Epoch 15/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5406 - accuracy: 0.7355 - val_loss: 0.5539 - val_accuracy: 0.7308
Epoch 16/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5405 - accuracy: 0.7352 - val_loss: 0.5543 - val_accuracy: 0.7302
Epoch 17/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5403 - accuracy: 0.7363 - val_loss: 0.5553 - val_accuracy: 0.7289
Epoch 18/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5397 - accuracy: 0.7358 - val_loss: 0.5530 - val_accuracy: 0.7299
Epoch 19/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5395 - accuracy: 0.7353 - val_loss: 0.5546 - val_accuracy: 0.7305
Epoch 20/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5398 - accuracy: 0.7366 - val_loss: 0.5521 - val_accuracy: 0.7322
Epoch 21/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5388 - accuracy: 0.7372 - val_loss: 0.5541 - val_accuracy: 0.7312
Epoch 22/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5390 - accuracy: 0.7375 - val_loss: 0.5522 - val_accuracy: 0.7313
Epoch 23/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5389 - accuracy: 0.7368 - val_loss: 0.5531 - val_accuracy: 0.7315
Epoch 24/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5392 - accuracy: 0.7362 - val_loss: 0.5536 - val_accuracy: 0.7306
Epoch 25/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5384 - accuracy: 0.7365 - val_loss: 0.5537 - val_accuracy: 0.7299
Epoch 26/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5383 - accuracy: 0.7369 - val_loss: 0.5524 - val_accuracy: 0.7280
Epoch 27/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5389 - accuracy: 0.7375 - val_loss: 0.5522 - val_accuracy: 0.7299
Epoch 28/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5373 - accuracy: 0.7370 - val_loss: 0.5546 - val_accuracy: 0.7293
Epoch 29/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5380 - accuracy: 0.7370 - val_loss: 0.5522 - val_accuracy: 0.7308
Epoch 30/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5372 - accuracy: 0.7377 - val_loss: 0.5554 - val_accuracy: 0.7300
Epoch 31/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5379 - accuracy: 0.7376 - val_loss: 0.5528 - val_accuracy: 0.7297
Epoch 32/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5370 - accuracy: 0.7375 - val_loss: 0.5550 - val_accuracy: 0.7299
Epoch 33/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5374 - accuracy: 0.7384 - val_loss: 0.5591 - val_accuracy: 0.7290
Epoch 34/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5374 - accuracy: 0.7374 - val_loss: 0.5543 - val_accuracy: 0.7294
Epoch 35/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5365 - accuracy: 0.7372 - val_loss: 0.5543 - val_accuracy: 0.7294
Epoch 36/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5370 - accuracy: 0.7378 - val_loss: 0.5553 - val_accuracy: 0.7297
Epoch 37/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5365 - accuracy: 0.7379 - val_loss: 0.5567 - val_accuracy: 0.7300
Epoch 38/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5364 - accuracy: 0.7381 - val_loss: 0.5557 - val_accuracy: 0.7294
Epoch 39/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5365 - accuracy: 0.7375 - val_loss: 0.5547 - val_accuracy: 0.7296
Epoch 40/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5362 - accuracy: 0.7379 - val_loss: 0.5553 - val_accuracy: 0.7294
Epoch 41/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5364 - accuracy: 0.7370 - val_loss: 0.5568 - val_accuracy: 0.7297
Epoch 42/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5358 - accuracy: 0.7391 - val_loss: 0.5579 - val_accuracy: 0.7289
Epoch 43/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5363 - accuracy: 0.7373 - val_loss: 0.5550 - val_accuracy: 0.7303
Epoch 44/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5357 - accuracy: 0.7388 - val_loss: 0.5577 - val_accuracy: 0.7309
Epoch 45/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5357 - accuracy: 0.7392 - val_loss: 0.5570 - val_accuracy: 0.7283
Epoch 46/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5357 - accuracy: 0.7383 - val_loss: 0.5551 - val_accuracy: 0.7303
Epoch 47/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5354 - accuracy: 0.7384 - val_loss: 0.5574 - val_accuracy: 0.7306
Epoch 48/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5352 - accuracy: 0.7396 - val_loss: 0.5558 - val_accuracy: 0.7302
Epoch 49/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5352 - accuracy: 0.7393 - val_loss: 0.5566 - val_accuracy: 0.7290
Epoch 50/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5355 - accuracy: 0.7389 - val_loss: 0.5562 - val_accuracy: 0.7309
Epoch 51/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5347 - accuracy: 0.7382 - val_loss: 0.5608 - val_accuracy: 0.7300
Epoch 52/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5352 - accuracy: 0.7397 - val_loss: 0.5578 - val_accuracy: 0.7300
Epoch 53/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5350 - accuracy: 0.7387 - val_loss: 0.5572 - val_accuracy: 0.7305
Epoch 54/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5347 - accuracy: 0.7385 - val_loss: 0.5586 - val_accuracy: 0.7305
Epoch 55/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5349 - accuracy: 0.7395 - val_loss: 0.5553 - val_accuracy: 0.7305
Epoch 56/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5345 - accuracy: 0.7394 - val_loss: 0.5576 - val_accuracy: 0.7293
Epoch 57/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5345 - accuracy: 0.7388 - val_loss: 0.5580 - val_accuracy: 0.7296
Epoch 58/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5341 - accuracy: 0.7395 - val_loss: 0.5586 - val_accuracy: 0.7293
Epoch 59/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5343 - accuracy: 0.7395 - val_loss: 0.5563 - val_accuracy: 0.7292
Epoch 60/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5343 - accuracy: 0.7386 - val_loss: 0.5596 - val_accuracy: 0.7309
Epoch 61/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5343 - accuracy: 0.7393 - val_loss: 0.5587 - val_accuracy: 0.7306
Epoch 62/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5341 - accuracy: 0.7388 - val_loss: 0.5586 - val_accuracy: 0.7300
Epoch 63/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5342 - accuracy: 0.7400 - val_loss: 0.5579 - val_accuracy: 0.7293
Epoch 64/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5343 - accuracy: 0.7393 - val_loss: 0.5610 - val_accuracy: 0.7294
Epoch 65/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5340 - accuracy: 0.7398 - val_loss: 0.5596 - val_accuracy: 0.7280
Epoch 66/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5339 - accuracy: 0.7393 - val_loss: 0.5642 - val_accuracy: 0.7309
Epoch 67/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5338 - accuracy: 0.7400 - val_loss: 0.5583 - val_accuracy: 0.7277
Epoch 68/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5336 - accuracy: 0.7388 - val_loss: 0.5610 - val_accuracy: 0.7268
Epoch 69/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5337 - accuracy: 0.7391 - val_loss: 0.5579 - val_accuracy: 0.7283
Epoch 70/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5334 - accuracy: 0.7396 - val_loss: 0.5611 - val_accuracy: 0.7277
Epoch 71/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5339 - accuracy: 0.7389 - val_loss: 0.5587 - val_accuracy: 0.7306
Epoch 72/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5334 - accuracy: 0.7390 - val_loss: 0.5623 - val_accuracy: 0.7280
Epoch 73/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5332 - accuracy: 0.7400 - val_loss: 0.5576 - val_accuracy: 0.7296
Epoch 74/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5332 - accuracy: 0.7396 - val_loss: 0.5604 - val_accuracy: 0.7276
Epoch 75/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5336 - accuracy: 0.7396 - val_loss: 0.5592 - val_accuracy: 0.7286
Epoch 76/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5332 - accuracy: 0.7405 - val_loss: 0.5619 - val_accuracy: 0.7281
Epoch 77/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5333 - accuracy: 0.7400 - val_loss: 0.5608 - val_accuracy: 0.7278
Epoch 78/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5334 - accuracy: 0.7397 - val_loss: 0.5615 - val_accuracy: 0.7277
Epoch 79/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5330 - accuracy: 0.7396 - val_loss: 0.5614 - val_accuracy: 0.7276
Epoch 80/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5334 - accuracy: 0.7392 - val_loss: 0.5592 - val_accuracy: 0.7281
Epoch 81/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5333 - accuracy: 0.7403 - val_loss: 0.5618 - val_accuracy: 0.7292
Epoch 82/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5326 - accuracy: 0.7393 - val_loss: 0.5626 - val_accuracy: 0.7274
Epoch 83/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5331 - accuracy: 0.7393 - val_loss: 0.5625 - val_accuracy: 0.7270
Epoch 84/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5333 - accuracy: 0.7393 - val_loss: 0.5613 - val_accuracy: 0.7290
Epoch 85/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5328 - accuracy: 0.7400 - val_loss: 0.5638 - val_accuracy: 0.7283
Epoch 86/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5332 - accuracy: 0.7395 - val_loss: 0.5609 - val_accuracy: 0.7280
Epoch 87/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5326 - accuracy: 0.7399 - val_loss: 0.5609 - val_accuracy: 0.7299
Epoch 88/100
2744/2744 [==============================] - 13s 5ms/step - loss: 0.5329 - accuracy: 0.7401 - val_loss: 0.5617 - val_accuracy: 0.7284
Epoch 89/100
2744/2744 [==============================] - 11s 4ms/step - loss: 0.5329 - accuracy: 0.7403 - val_loss: 0.5598 - val_accuracy: 0.7308
Epoch 90/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5327 - accuracy: 0.7400 - val_loss: 0.5610 - val_accuracy: 0.7287
Epoch 91/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5326 - accuracy: 0.7399 - val_loss: 0.5602 - val_accuracy: 0.7308
Epoch 92/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5331 - accuracy: 0.7397 - val_loss: 0.5594 - val_accuracy: 0.7313
Epoch 93/100
2744/2744 [==============================] - 11s 4ms/step - loss: 0.5325 - accuracy: 0.7400 - val_loss: 0.5598 - val_accuracy: 0.7316
Epoch 94/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5323 - accuracy: 0.7399 - val_loss: 0.5661 - val_accuracy: 0.7290
Epoch 95/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5325 - accuracy: 0.7393 - val_loss: 0.5629 - val_accuracy: 0.7292
Epoch 96/100
2744/2744 [==============================] - 11s 4ms/step - loss: 0.5327 - accuracy: 0.7404 - val_loss: 0.5623 - val_accuracy: 0.7296
Epoch 97/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5326 - accuracy: 0.7400 - val_loss: 0.5669 - val_accuracy: 0.7280
Epoch 98/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5328 - accuracy: 0.7397 - val_loss: 0.5613 - val_accuracy: 0.7306
Epoch 99/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5325 - accuracy: 0.7400 - val_loss: 0.5594 - val_accuracy: 0.7305
Epoch 100/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5325 - accuracy: 0.7405 - val_loss: 0.5612 - val_accuracy: 0.7292

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")