In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME', 'USE_CASE', 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS'], axis=1, inplace=True)

In [ ]:
# Determine the number of unique values in each column.
unique = application_df.nunique()
print(unique)

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
STATUS                 2
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
applications = application_df['APPLICATION_TYPE'].value_counts()
print(applications)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = applications[applications < 500].index.tolist()
print(application_types_to_replace)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = classification_counts[classification_counts > 1]
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 100].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
encoded = pd.get_dummies(application_df)
print(encoded.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                   False
1       1   108590              1                   False
2       1     5000              0                   False
3       1     6692              1                   False
4       1   142590              1                   False

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                  True                 False                False
1                 False                 False                 True
2                 False                 False                False
3                 False                 False                 True
4                 False                 False                 True

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                False                False                False  ...
1                False                False                False  ...
2                False                 True                False  ...
3                False                False                False  ...
4                False                False                False  ...

   CLASSIFICATION_Other  INCOME_AMT_0  INCOME_AMT_1-9999  \
0                 False          True              False
1                 False         False               True
2                 False          True              False
3                 False         False              False
4                 False         False              False

   INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  \
0                   False                     False               False
1                   False                     False               False
2                   False                     False               False
3                    True                     False               False
4                   False                      True               False

   INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  INCOME_AMT_50M+  \
0             False                   False            False
1             False                   False            False
2             False                   False            False
3             False                   False            False
4             False                   False            False

   INCOME_AMT_5M-10M
0              False
1              False
2              False
3              False
4              False

[5 rows x 65 columns]

In [ ]:
# Split our preprocessed data into our features and target arrays
X = encoded.drop(['IS_SUCCESSFUL'], axis=1)
y = encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                5200

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 7661 (29.93 KB)
Trainable params: 7661 (29.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
nnmodel2 = nn.fit(X_train_scaled, y_train, epochs=100, batch_size=10, validation_data=(X_test_scaled, y_test))

Epoch 1/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5745 - accuracy: 0.7207 - val_loss: 0.5686 - val_accuracy: 0.7238
Epoch 2/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5623 - accuracy: 0.7258 - val_loss: 0.5695 - val_accuracy: 0.7230
Epoch 3/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5602 - accuracy: 0.7272 - val_loss: 0.5681 - val_accuracy: 0.7267
Epoch 4/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5599 - accuracy: 0.7279 - val_loss: 0.5650 - val_accuracy: 0.7252
Epoch 5/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5597 - accuracy: 0.7279 - val_loss: 0.5671 - val_accuracy: 0.7277
Epoch 6/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5584 - accuracy: 0.7294 - val_loss: 0.5687 - val_accuracy: 0.7239
Epoch 7/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5582 - accuracy: 0.7289 - val_loss: 0.5651 - val_accuracy: 0.7270
Epoch 8/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5578 - accuracy: 0.7292 - val_loss: 0.5650 - val_accuracy: 0.7268
Epoch 9/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5575 - accuracy: 0.7281 - val_loss: 0.5663 - val_accuracy: 0.7276
Epoch 10/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5573 - accuracy: 0.7299 - val_loss: 0.5674 - val_accuracy: 0.7246
Epoch 11/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5571 - accuracy: 0.7295 - val_loss: 0.5637 - val_accuracy: 0.7252
Epoch 12/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5567 - accuracy: 0.7299 - val_loss: 0.5668 - val_accuracy: 0.7254
Epoch 13/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5570 - accuracy: 0.7294 - val_loss: 0.5651 - val_accuracy: 0.7249
Epoch 14/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5566 - accuracy: 0.7295 - val_loss: 0.5674 - val_accuracy: 0.7273
Epoch 15/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5564 - accuracy: 0.7298 - val_loss: 0.5653 - val_accuracy: 0.7258
Epoch 16/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5561 - accuracy: 0.7298 - val_loss: 0.5633 - val_accuracy: 0.7254
Epoch 17/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5561 - accuracy: 0.7299 - val_loss: 0.5639 - val_accuracy: 0.7273
Epoch 18/100
2744/2744 [==============================] - 10s 4ms/step - loss: 0.5556 - accuracy: 0.7299 - val_loss: 0.5650 - val_accuracy: 0.7242
Epoch 19/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5557 - accuracy: 0.7292 - val_loss: 0.5659 - val_accuracy: 0.7245
Epoch 20/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5553 - accuracy: 0.7299 - val_loss: 0.5673 - val_accuracy: 0.7264
Epoch 21/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5553 - accuracy: 0.7304 - val_loss: 0.5655 - val_accuracy: 0.7262
Epoch 22/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5550 - accuracy: 0.7304 - val_loss: 0.5643 - val_accuracy: 0.7245
Epoch 23/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5549 - accuracy: 0.7306 - val_loss: 0.5659 - val_accuracy: 0.7254
Epoch 24/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5550 - accuracy: 0.7304 - val_loss: 0.5652 - val_accuracy: 0.7264
Epoch 25/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5544 - accuracy: 0.7309 - val_loss: 0.5668 - val_accuracy: 0.7249
Epoch 26/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5545 - accuracy: 0.7309 - val_loss: 0.5662 - val_accuracy: 0.7271
Epoch 27/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5545 - accuracy: 0.7305 - val_loss: 0.5673 - val_accuracy: 0.7264
Epoch 28/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5544 - accuracy: 0.7310 - val_loss: 0.5655 - val_accuracy: 0.7243
Epoch 29/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5541 - accuracy: 0.7308 - val_loss: 0.5666 - val_accuracy: 0.7265
Epoch 30/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5542 - accuracy: 0.7310 - val_loss: 0.5658 - val_accuracy: 0.7262
Epoch 31/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5542 - accuracy: 0.7307 - val_loss: 0.5644 - val_accuracy: 0.7268
Epoch 32/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5545 - accuracy: 0.7314 - val_loss: 0.5675 - val_accuracy: 0.7229
Epoch 33/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5544 - accuracy: 0.7305 - val_loss: 0.5668 - val_accuracy: 0.7262
Epoch 34/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5546 - accuracy: 0.7311 - val_loss: 0.5678 - val_accuracy: 0.7246
Epoch 35/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5539 - accuracy: 0.7321 - val_loss: 0.5684 - val_accuracy: 0.7251
Epoch 36/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5538 - accuracy: 0.7307 - val_loss: 0.5669 - val_accuracy: 0.7276
Epoch 37/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5538 - accuracy: 0.7306 - val_loss: 0.5680 - val_accuracy: 0.7255
Epoch 38/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5542 - accuracy: 0.7308 - val_loss: 0.5678 - val_accuracy: 0.7254
Epoch 39/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5535 - accuracy: 0.7314 - val_loss: 0.5678 - val_accuracy: 0.7257
Epoch 40/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5536 - accuracy: 0.7313 - val_loss: 0.5672 - val_accuracy: 0.7264
Epoch 41/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5541 - accuracy: 0.7305 - val_loss: 0.5662 - val_accuracy: 0.7270
Epoch 42/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5535 - accuracy: 0.7312 - val_loss: 0.5671 - val_accuracy: 0.7257
Epoch 43/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5537 - accuracy: 0.7315 - val_loss: 0.5688 - val_accuracy: 0.7235
Epoch 44/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5539 - accuracy: 0.7312 - val_loss: 0.5671 - val_accuracy: 0.7270
Epoch 45/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5533 - accuracy: 0.7315 - val_loss: 0.5680 - val_accuracy: 0.7255
Epoch 46/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5534 - accuracy: 0.7317 - val_loss: 0.5680 - val_accuracy: 0.7246
Epoch 47/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5538 - accuracy: 0.7310 - val_loss: 0.5662 - val_accuracy: 0.7276
Epoch 48/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5535 - accuracy: 0.7315 - val_loss: 0.5687 - val_accuracy: 0.7258
Epoch 49/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5529 - accuracy: 0.7312 - val_loss: 0.5687 - val_accuracy: 0.7233
Epoch 50/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5533 - accuracy: 0.7308 - val_loss: 0.5687 - val_accuracy: 0.7265
Epoch 51/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5531 - accuracy: 0.7310 - val_loss: 0.5725 - val_accuracy: 0.7232
Epoch 52/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5531 - accuracy: 0.7304 - val_loss: 0.5683 - val_accuracy: 0.7264
Epoch 53/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5533 - accuracy: 0.7317 - val_loss: 0.5705 - val_accuracy: 0.7264
Epoch 54/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5530 - accuracy: 0.7309 - val_loss: 0.5692 - val_accuracy: 0.7267
Epoch 55/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5533 - accuracy: 0.7310 - val_loss: 0.5699 - val_accuracy: 0.7226
Epoch 56/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5525 - accuracy: 0.7315 - val_loss: 0.5720 - val_accuracy: 0.7258
Epoch 57/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5531 - accuracy: 0.7310 - val_loss: 0.5673 - val_accuracy: 0.7264
Epoch 58/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5531 - accuracy: 0.7307 - val_loss: 0.5672 - val_accuracy: 0.7258
Epoch 59/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5531 - accuracy: 0.7311 - val_loss: 0.5688 - val_accuracy: 0.7255
Epoch 60/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5551 - accuracy: 0.7310 - val_loss: 0.5682 - val_accuracy: 0.7242
Epoch 61/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5526 - accuracy: 0.7309 - val_loss: 0.5684 - val_accuracy: 0.7276
Epoch 62/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5527 - accuracy: 0.7315 - val_loss: 0.5705 - val_accuracy: 0.7252
Epoch 63/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5530 - accuracy: 0.7319 - val_loss: 0.5732 - val_accuracy: 0.7276
Epoch 64/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5527 - accuracy: 0.7315 - val_loss: 0.5692 - val_accuracy: 0.7258
Epoch 65/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5528 - accuracy: 0.7318 - val_loss: 0.5706 - val_accuracy: 0.7268
Epoch 66/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5529 - accuracy: 0.7313 - val_loss: 0.5680 - val_accuracy: 0.7271
Epoch 67/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5525 - accuracy: 0.7316 - val_loss: 0.5694 - val_accuracy: 0.7255
Epoch 68/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5534 - accuracy: 0.7315 - val_loss: 0.5657 - val_accuracy: 0.7264
Epoch 69/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5525 - accuracy: 0.7313 - val_loss: 0.5703 - val_accuracy: 0.7246
Epoch 70/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5528 - accuracy: 0.7315 - val_loss: 0.5687 - val_accuracy: 0.7248
Epoch 71/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5524 - accuracy: 0.7310 - val_loss: 0.5670 - val_accuracy: 0.7254
Epoch 72/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5527 - accuracy: 0.7319 - val_loss: 0.5687 - val_accuracy: 0.7267
Epoch 73/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5527 - accuracy: 0.7316 - val_loss: 0.5693 - val_accuracy: 0.7249
Epoch 74/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5521 - accuracy: 0.7310 - val_loss: 0.5688 - val_accuracy: 0.7270
Epoch 75/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5528 - accuracy: 0.7313 - val_loss: 0.5672 - val_accuracy: 0.7264
Epoch 76/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5523 - accuracy: 0.7311 - val_loss: 0.5732 - val_accuracy: 0.7280
Epoch 77/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5524 - accuracy: 0.7315 - val_loss: 0.5700 - val_accuracy: 0.7274
Epoch 78/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5523 - accuracy: 0.7317 - val_loss: 0.5688 - val_accuracy: 0.7264
Epoch 79/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5527 - accuracy: 0.7313 - val_loss: 0.5703 - val_accuracy: 0.7261
Epoch 80/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5523 - accuracy: 0.7314 - val_loss: 0.5695 - val_accuracy: 0.7264
Epoch 81/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5523 - accuracy: 0.7314 - val_loss: 0.5704 - val_accuracy: 0.7267
Epoch 82/100
2744/2744 [==============================] - 10s 4ms/step - loss: 0.5523 - accuracy: 0.7317 - val_loss: 0.5670 - val_accuracy: 0.7264
Epoch 83/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5524 - accuracy: 0.7321 - val_loss: 0.5710 - val_accuracy: 0.7258
Epoch 84/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5531 - accuracy: 0.7312 - val_loss: 0.5729 - val_accuracy: 0.7262
Epoch 85/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5521 - accuracy: 0.7317 - val_loss: 0.5719 - val_accuracy: 0.7238
Epoch 86/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5517 - accuracy: 0.7310 - val_loss: 0.5713 - val_accuracy: 0.7243
Epoch 87/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5523 - accuracy: 0.7317 - val_loss: 0.5698 - val_accuracy: 0.7271
Epoch 88/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5520 - accuracy: 0.7312 - val_loss: 0.5714 - val_accuracy: 0.7280
Epoch 89/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5524 - accuracy: 0.7315 - val_loss: 0.5765 - val_accuracy: 0.7257
Epoch 90/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5518 - accuracy: 0.7318 - val_loss: 0.5731 - val_accuracy: 0.7265
Epoch 91/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5535 - accuracy: 0.7322 - val_loss: 0.5744 - val_accuracy: 0.7270
Epoch 92/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5596 - accuracy: 0.7324 - val_loss: 0.5710 - val_accuracy: 0.7270
Epoch 93/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5515 - accuracy: 0.7322 - val_loss: 0.5730 - val_accuracy: 0.7242
Epoch 94/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5517 - accuracy: 0.7315 - val_loss: 0.5703 - val_accuracy: 0.7267
Epoch 95/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5522 - accuracy: 0.7309 - val_loss: 0.5721 - val_accuracy: 0.7264
Epoch 96/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5517 - accuracy: 0.7307 - val_loss: 0.5778 - val_accuracy: 0.7249
Epoch 97/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5522 - accuracy: 0.7318 - val_loss: 0.5693 - val_accuracy: 0.7274
Epoch 98/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5516 - accuracy: 0.7318 - val_loss: 0.5778 - val_accuracy: 0.7258
Epoch 99/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5520 - accuracy: 0.7311 - val_loss: 0.5714 - val_accuracy: 0.7273
Epoch 100/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5523 - accuracy: 0.7315 - val_loss: 0.5763 - val_accuracy: 0.7220

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")