## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)

In [3]:
# Determine the number of unique values in each column.
unique = application_df.nunique()
print(unique)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
applications = application_df['APPLICATION_TYPE'].value_counts()
print(applications)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = applications[applications < 500].index.tolist()
print(application_types_to_replace)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = classification_counts[classification_counts > 1]
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 100].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
encoded = pd.get_dummies(application_df)
print(encoded.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                   False
1       1   108590              1                   False
2       1     5000              0                   False
3       1     6692              1                   False
4       1   142590              1                   False

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                  True                 False                False
1                 False                 False                 True
2                 False                 False                False
3                 False                 False                 True
4                 False                 False                 True

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                False                False                False  ...
1                False                False                False  ...
2                False                 True                False  ...
3                False                False                False  ...
4                False                False                False  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0              False                   False                     False
1               True                   False                     False
2              False                   False                     False
3              False                    True                     False
4              False                   False                      True

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0               False             False                   False
1               False             False                   False
2               False             False                   False
3               False             False                   False
4               False             False                   False

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0            False              False                      True
1            False              False                      True
2            False              False                      True
3            False              False                      True
4            False              False                      True

   SPECIAL_CONSIDERATIONS_Y
0                     False
1                     False
2                     False
3                     False
4                     False

[5 rows x 76 columns]

In [10]:
# Split our preprocessed data into our features and target arrays
X = encoded.drop(['IS_SUCCESSFUL'], axis=1)
y = encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                6080

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 8541 (33.36 KB)
Trainable params: 8541 (33.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [14]:
# Train the model
nnmodel = nn.fit(X_train_scaled, y_train, epochs=100, batch_size=10, validation_data=(X_test_scaled, y_test))

Epoch 1/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5677 - accuracy: 0.7245 - val_loss: 0.5618 - val_accuracy: 0.7242
Epoch 2/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5525 - accuracy: 0.7304 - val_loss: 0.5578 - val_accuracy: 0.7188
Epoch 3/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5492 - accuracy: 0.7312 - val_loss: 0.5570 - val_accuracy: 0.7243
Epoch 4/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5476 - accuracy: 0.7324 - val_loss: 0.5572 - val_accuracy: 0.7265
Epoch 5/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5474 - accuracy: 0.7334 - val_loss: 0.5534 - val_accuracy: 0.7270
Epoch 6/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5450 - accuracy: 0.7330 - val_loss: 0.5548 - val_accuracy: 0.7309
Epoch 7/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5448 - accuracy: 0.7331 - val_loss: 0.5554 - val_accuracy: 0.7277
Epoch 8/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5440 - accuracy: 0.7350 - val_loss: 0.5526 - val_accuracy: 0.7236
Epoch 9/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5438 - accuracy: 0.7335 - val_loss: 0.5544 - val_accuracy: 0.7276
Epoch 10/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5433 - accuracy: 0.7337 - val_loss: 0.5549 - val_accuracy: 0.7290
Epoch 11/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5425 - accuracy: 0.7345 - val_loss: 0.5527 - val_accuracy: 0.7286
Epoch 12/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5414 - accuracy: 0.7353 - val_loss: 0.5520 - val_accuracy: 0.7283
Epoch 13/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5414 - accuracy: 0.7366 - val_loss: 0.5493 - val_accuracy: 0.7294
Epoch 14/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5412 - accuracy: 0.7357 - val_loss: 0.5509 - val_accuracy: 0.7277
Epoch 15/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5407 - accuracy: 0.7365 - val_loss: 0.5512 - val_accuracy: 0.7300
Epoch 16/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5406 - accuracy: 0.7369 - val_loss: 0.5513 - val_accuracy: 0.7310
Epoch 17/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5396 - accuracy: 0.7368 - val_loss: 0.5519 - val_accuracy: 0.7297
Epoch 18/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5394 - accuracy: 0.7366 - val_loss: 0.5526 - val_accuracy: 0.7271
Epoch 19/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5390 - accuracy: 0.7365 - val_loss: 0.5561 - val_accuracy: 0.7286
Epoch 20/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5397 - accuracy: 0.7369 - val_loss: 0.5532 - val_accuracy: 0.7281
Epoch 21/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5391 - accuracy: 0.7377 - val_loss: 0.5503 - val_accuracy: 0.7292
Epoch 22/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5381 - accuracy: 0.7381 - val_loss: 0.5540 - val_accuracy: 0.7227
Epoch 23/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5383 - accuracy: 0.7373 - val_loss: 0.5514 - val_accuracy: 0.7325
Epoch 24/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5377 - accuracy: 0.7375 - val_loss: 0.5519 - val_accuracy: 0.7305
Epoch 25/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5375 - accuracy: 0.7386 - val_loss: 0.5544 - val_accuracy: 0.7299
Epoch 26/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5375 - accuracy: 0.7380 - val_loss: 0.5524 - val_accuracy: 0.7296
Epoch 27/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5373 - accuracy: 0.7379 - val_loss: 0.5541 - val_accuracy: 0.7296
Epoch 28/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5371 - accuracy: 0.7374 - val_loss: 0.5525 - val_accuracy: 0.7302
Epoch 29/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5372 - accuracy: 0.7383 - val_loss: 0.5523 - val_accuracy: 0.7299
Epoch 30/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5368 - accuracy: 0.7383 - val_loss: 0.5526 - val_accuracy: 0.7305
Epoch 31/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5369 - accuracy: 0.7385 - val_loss: 0.5525 - val_accuracy: 0.7296
Epoch 32/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5367 - accuracy: 0.7389 - val_loss: 0.5562 - val_accuracy: 0.7254
Epoch 33/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5361 - accuracy: 0.7385 - val_loss: 0.5538 - val_accuracy: 0.7300
Epoch 34/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5356 - accuracy: 0.7392 - val_loss: 0.5533 - val_accuracy: 0.7297
Epoch 35/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5360 - accuracy: 0.7385 - val_loss: 0.5536 - val_accuracy: 0.7313
Epoch 36/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5361 - accuracy: 0.7393 - val_loss: 0.5524 - val_accuracy: 0.7308
Epoch 37/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5355 - accuracy: 0.7385 - val_loss: 0.5523 - val_accuracy: 0.7297
Epoch 38/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5353 - accuracy: 0.7389 - val_loss: 0.5548 - val_accuracy: 0.7284
Epoch 39/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5361 - accuracy: 0.7391 - val_loss: 0.5543 - val_accuracy: 0.7321
Epoch 40/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5348 - accuracy: 0.7395 - val_loss: 0.5545 - val_accuracy: 0.7299
Epoch 41/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5348 - accuracy: 0.7385 - val_loss: 0.5558 - val_accuracy: 0.7305
Epoch 42/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5362 - accuracy: 0.7384 - val_loss: 0.5556 - val_accuracy: 0.7309
Epoch 43/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5348 - accuracy: 0.7392 - val_loss: 0.5555 - val_accuracy: 0.7290
Epoch 44/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5350 - accuracy: 0.7387 - val_loss: 0.5573 - val_accuracy: 0.7296
Epoch 45/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5353 - accuracy: 0.7385 - val_loss: 0.5584 - val_accuracy: 0.7293
Epoch 46/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5343 - accuracy: 0.7390 - val_loss: 0.5572 - val_accuracy: 0.7299
Epoch 47/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5344 - accuracy: 0.7391 - val_loss: 0.5569 - val_accuracy: 0.7308
Epoch 48/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5349 - accuracy: 0.7388 - val_loss: 0.5591 - val_accuracy: 0.7312
Epoch 49/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5337 - accuracy: 0.7392 - val_loss: 0.5586 - val_accuracy: 0.7321
Epoch 50/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5341 - accuracy: 0.7392 - val_loss: 0.5554 - val_accuracy: 0.7331
Epoch 51/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5344 - accuracy: 0.7386 - val_loss: 0.5571 - val_accuracy: 0.7319
Epoch 52/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5340 - accuracy: 0.7390 - val_loss: 0.5604 - val_accuracy: 0.7319
Epoch 53/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5343 - accuracy: 0.7396 - val_loss: 0.5563 - val_accuracy: 0.7318
Epoch 54/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5339 - accuracy: 0.7402 - val_loss: 0.5593 - val_accuracy: 0.7318
Epoch 55/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5340 - accuracy: 0.7395 - val_loss: 0.5574 - val_accuracy: 0.7274
Epoch 56/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5407 - accuracy: 0.7402 - val_loss: 0.5583 - val_accuracy: 0.7293
Epoch 57/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5335 - accuracy: 0.7408 - val_loss: 0.5578 - val_accuracy: 0.7300
Epoch 58/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5339 - accuracy: 0.7401 - val_loss: 0.5587 - val_accuracy: 0.7294
Epoch 59/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5333 - accuracy: 0.7389 - val_loss: 0.5589 - val_accuracy: 0.7318
Epoch 60/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5334 - accuracy: 0.7392 - val_loss: 0.5620 - val_accuracy: 0.7308
Epoch 61/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5332 - accuracy: 0.7402 - val_loss: 0.5606 - val_accuracy: 0.7316
Epoch 62/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5337 - accuracy: 0.7397 - val_loss: 0.5587 - val_accuracy: 0.7308
Epoch 63/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5345 - accuracy: 0.7398 - val_loss: 0.5593 - val_accuracy: 0.7308
Epoch 64/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5330 - accuracy: 0.7402 - val_loss: 0.5596 - val_accuracy: 0.7303
Epoch 65/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5328 - accuracy: 0.7399 - val_loss: 0.5611 - val_accuracy: 0.7300
Epoch 66/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5333 - accuracy: 0.7397 - val_loss: 0.5604 - val_accuracy: 0.7299
Epoch 67/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5330 - accuracy: 0.7395 - val_loss: 0.5647 - val_accuracy: 0.7306
Epoch 68/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5420 - accuracy: 0.7399 - val_loss: 0.5609 - val_accuracy: 0.7296
Epoch 69/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5325 - accuracy: 0.7402 - val_loss: 0.5595 - val_accuracy: 0.7310
Epoch 70/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5326 - accuracy: 0.7400 - val_loss: 0.5597 - val_accuracy: 0.7302
Epoch 71/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5326 - accuracy: 0.7397 - val_loss: 0.5639 - val_accuracy: 0.7299
Epoch 72/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5325 - accuracy: 0.7407 - val_loss: 0.5656 - val_accuracy: 0.7296
Epoch 73/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5332 - accuracy: 0.7397 - val_loss: 0.5610 - val_accuracy: 0.7292
Epoch 74/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5328 - accuracy: 0.7404 - val_loss: 0.5629 - val_accuracy: 0.7289
Epoch 75/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5404 - accuracy: 0.7394 - val_loss: 0.5618 - val_accuracy: 0.7297
Epoch 76/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5323 - accuracy: 0.7405 - val_loss: 0.5623 - val_accuracy: 0.7302
Epoch 77/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5323 - accuracy: 0.7409 - val_loss: 0.5635 - val_accuracy: 0.7312
Epoch 78/100
2744/2744 [==============================] - 8s 3ms/step - loss: 0.5452 - accuracy: 0.7398 - val_loss: 0.5625 - val_accuracy: 0.7305
Epoch 79/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5319 - accuracy: 0.7398 - val_loss: 0.5630 - val_accuracy: 0.7312
Epoch 80/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5319 - accuracy: 0.7405 - val_loss: 0.5615 - val_accuracy: 0.7310
Epoch 81/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5324 - accuracy: 0.7409 - val_loss: 0.5653 - val_accuracy: 0.7292
Epoch 82/100
2744/2744 [==============================] - 9s 3ms/step - loss: 0.5326 - accuracy: 0.7404 - val_loss: 0.5622 - val_accuracy: 0.7308
Epoch 83/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5323 - accuracy: 0.7407 - val_loss: 0.5684 - val_accuracy: 0.7310
Epoch 84/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5322 - accuracy: 0.7406 - val_loss: 0.5650 - val_accuracy: 0.7309
Epoch 85/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5320 - accuracy: 0.7407 - val_loss: 0.5655 - val_accuracy: 0.7310
Epoch 86/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5319 - accuracy: 0.7401 - val_loss: 0.5647 - val_accuracy: 0.7293
Epoch 87/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5336 - accuracy: 0.7401 - val_loss: 0.5616 - val_accuracy: 0.7305
Epoch 88/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5323 - accuracy: 0.7406 - val_loss: 0.5629 - val_accuracy: 0.7308
Epoch 89/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5320 - accuracy: 0.7405 - val_loss: 0.5644 - val_accuracy: 0.7305
Epoch 90/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5322 - accuracy: 0.7409 - val_loss: 0.5663 - val_accuracy: 0.7303
Epoch 91/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5324 - accuracy: 0.7402 - val_loss: 0.5646 - val_accuracy: 0.7318
Epoch 92/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5319 - accuracy: 0.7404 - val_loss: 0.5668 - val_accuracy: 0.7331
Epoch 93/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5322 - accuracy: 0.7404 - val_loss: 0.5634 - val_accuracy: 0.7305
Epoch 94/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5324 - accuracy: 0.7405 - val_loss: 0.5696 - val_accuracy: 0.7296
Epoch 95/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5614 - accuracy: 0.7398 - val_loss: 0.5678 - val_accuracy: 0.7289
Epoch 96/100
2744/2744 [==============================] - 7s 2ms/step - loss: 0.5311 - accuracy: 0.7407 - val_loss: 0.5667 - val_accuracy: 0.7297
Epoch 97/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5314 - accuracy: 0.7404 - val_loss: 0.5650 - val_accuracy: 0.7292
Epoch 98/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5313 - accuracy: 0.7400 - val_loss: 0.5641 - val_accuracy: 0.7303
Epoch 99/100
2744/2744 [==============================] - 7s 3ms/step - loss: 0.5318 - accuracy: 0.7403 - val_loss: 0.5639 - val_accuracy: 0.7310
Epoch 100/100
2744/2744 [==============================] - 6s 2ms/step - loss: 0.5499 - accuracy: 0.7407 - val_loss: 0.5646 - val_accuracy: 0.7299

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5646 - accuracy: 0.7299 - 352ms/epoch - 2ms/step
Loss: 0.5646354556083679, Accuracy: 0.7298833727836609

In [16]:
# Export our model to HDF5 file
nn.save('model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(